### ISSUE TITLE
Is it possible to add parachain "Name" to xcm-global-registry/xcmRegistry ?

### ISSUE THREAD

**Issue by kopeboy** [colorfulnotion/xcm-global-registry#25]
I think we miss a way to fetch the chain/parachain names..
Maybe integrate https://github.com/paritytech/polkadot_network_directory ?

**Comment by mkchungs** [comment]
Can you provide an example what you want to see inside of xcm-global-registry/xcmRegistry?

FYI, chain name is already available at publicEndpoints directory(but not included in xcmRegistry yet): https://github.com/colorfulnotion/xcm-global-registry/blob/main/publicEndpoints/polkadot_publicEndpoints.json

**Comment by mkchungs** [comment]
@kopeboy: I've added `nativechainID` to [xcmRegistry.json](https://cdn.jsdelivr.net/gh/colorfulnotion/xcm-global-registry@latest/xcmRegistry/polkadot_xcmRegistry.json) in PR #27 (whenever available)

Hope you find it helpful.

 -- Michael

**Comment by kopeboy** [comment]
Good, thank you.

Side question: what's the difference between xcmRegistry and xcAssets?

**Comment by mkchungs** [comment]
* [xcmRegistry.json](https://cdn.jsdelivr.net/gh/colorfulnotion/xcm-global-registry@latest/xcmRegistry/polkadot_xcmRegistry.json) - aggregates all parachains' multilocations into one JSON file(keyed by same multilocation) - IMO, this format is a lot easier to ingest when you are building multi-chain applications 
* [xcAssets](https://github.com/colorfulnotion/xcm-global-registry/tree/main/xcAssets/polkadot) is parachain-specific registry published by each team on-chain. These files are **not aggregated** with sibling parachains, therefore should be "easier" for each team to look at when issues arise

* [xcmgar.json](https://github.com/colorfulnotion/xcm-global-registry/blob/main/metadata/xcmgar.json) - combines {Assets, xcAsset, xcmRegistry} in one JSON. Colorfulnotion uses this metadata JSON for other projects like [substrate-etl](https://github.com/colorfulnotion/substrate-etl) and [polkaholic](https://github.com/colorfulnotion/polkaholic)
