### ISSUE TITLE
Add Reserve/Teleport information to assets

### ISSUE THREAD

**Issue by acatangiu** [colorfulnotion/xcm-global-registry#48]
Suggesting more (meta)information to add to assets in this registry:

- **trusted reserve locations** - local ecosystem reserve chains; right now, for most assets it will be just the `originChain`, but hopefully in the near future, most assets will also have reserve on local `AssetHub`. Bridged assets also need a local reserve, either AssetHub or the parachain that bridged them in.
- **teleport locations** - local chains that support teleporting asset between them; this list will be identical to the "trusted reserve locations" list above, so we might skip it, but we could also explicitly add it.

Having this would be very useful to the ecosystem, and significantly reduce complexity in figuring out how to transfer these assets between chains. Right now, information on asset reserve locations or teleport locations is very hard to come by.

We can then create tooling for automated building of asset transfer XCMs, based on the information in this registry.

**Comment by mkchungs** [comment]
not planned
